<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>Firma Digital</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Mobile Specific Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- FONT -->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400italic,400,700,800,600' rel='stylesheet' type='text/css'>

    <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-64078199-1', 'auto');
        ga('send', 'pageview');

    </script>

    <!-- CSS -->
    <?php $this->headLink()->appendStylesheet('/css/normalize.css'); ?>
    <?php $this->headLink()->appendStylesheet('/css/skeleton.css'); ?>
    <?php $this->headLink()->appendStylesheet('/css/layout.css'); ?>
    <?php echo $this->headLink()->appendStylesheet('/css/vendor/jquery-ui.css'); ?>

    <!-- JS -->
    <?php $this->headScript()->prependFile('/js/Definitions.js'); ?>
    <?php $this->headScript()->prependFile('/js/vendor/jquery_dateentry/jquery.dateentry.js'); ?>
    <?php $this->headScript()->prependFile('/js/vendor/jquery_dateentry/jquery.plugin.js'); ?>
    <?php $this->headScript()->prependFile('/js/vendor/jquery-ui.js'); ?>
    <?php $this->headScript()->prependFile('/js/vendor/jquery-ui.js'); ?>
    <?php echo $this->headScript()->prependFile('/js/vendor/jquery.js'); ?>
    <link rel="icon" type="image/png" href="/images/favicon.png">
</head>
<body>
    <div class="top">
        <div class="container">
            <div class="row">
                <div class="two-thirds column header">
                    Firma Digital
                </div>
                <div class="one-third column logo">
                    <img src="/images/logo.png" width="127" height="127">
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <?php echo $this->layout()->content; ?>
    </div>
</body>
</html>