<div class="row">
    <div class="one-half column">
        <h1>Headers h1</h1>
        <h2>Headers h2</h2>
        <h3>Headers h3</h3>
        <h4>Headers h4</h4>
        <h5>Headers h5</h5>
        <h6>Headers h6</h6>
    </div>
    <div class="one-half column">
        <p>This is a paragraph example. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam id fermentum augue. Aliquam erat volutpat. Mauris bibendum mauris vitae condimentum volutpat. Pellentesque ut mi ultricies, eleifend turpis ac, suscipit leo. Etiam commodo arcu in sapien mollis, et vehicula urna lacinia. Curabitur sapien risus, faucibus tristique porta a, lacinia nec urna. Vestibulum pellentesque bibendum nibh a fringilla. Ut placerat pharetra gravida. </p>
        <p><a href="#">Link example</a></p>
        <input type="button" value="button input">
        <input class="button-primary" type="button" value="button input">
    </div>
</div>
<form>
    <div class="row">
        <div class="six columns">
            <label for="exampleEmailInput">Your email</label>
            <input class="u-full-width" type="email" placeholder="test@mailbox.com" id="exampleEmailInput">
        </div>
        <div class="six columns">
            <label for="exampleRecipientInput">Reason for contacting</label>
            <select class="u-full-width" id="exampleRecipientInput">
                <option value="Option 1">Questions</option>
                <option value="Option 2">Admiration</option>
                <option value="Option 3">Can I get your number?</option>
            </select>
        </div>
    </div>
    <label for="exampleMessage">Message</label>
    <textarea class="u-full-width" placeholder="Hi Dave …" id="exampleMessage"></textarea>
    <label class="example-send-yourself-copy">
        <input type="checkbox">
        <span class="label-body">Send a copy to yourself</span>
    </label>
    <input class="button-primary" type="submit" value="Submit">
</form>